apiVersion: v1
kind: ReplicationController
metadata:
  name: ubt-web-rc
spec:
  replicas: 5
  selector:
    app: ubt-web
    version: v1.0
  template:
    metadata:
      labels:
        app: ubt-web
        version: v1.0
    spec:
      containers:
      - name: ubt-web
        image: ubt/demo:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8000

