apiVersion: v1
kind: Service
metadata:
  name: ubt-web-svc
  labels:
    app: ubt-web
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30001
    protocol: TCP
  selector:
    app: ubt-web
